[package]
name = "byreal-clmm"
version = "0.1.0"
description = "Anchor client and source for Byreal concentrated liquidity AMM"
edition = "2021"
keywords = ["solana", "anchor", "byreal"]

[lib]
crate-type = ["cdylib", "lib"]
name = "byreal_clmm"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
client = []
no-log-ix-name = []
enable-log = []
localnet = []
devnet = []
paramset = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "1.0.2", features = ["init-if-needed"] }
anchor-spl = { version = "1.0.2", features = ["metadata", "memo"] }
spl-token-2022-interface = "2"
uint = { git = "https://github.com/raydium-io/parity-common", package = "uint" }
bytemuck = { version = "1.19.0", features = ["derive", "min_const_generics"] }
arrayref = { version = "0.3.6" }
solana-security-txt = "1.1.1"
# Pinned to match anchor 0.31.1
pyth-solana-receiver-sdk = { git = "https://github.com/jup-ag/pyth-crosschain.git", rev = "f80b82011a227ab541a0b16b3eb57a15bf6a0ad6" }

[dev-dependencies]
quickcheck = "0.9"
proptest = "1.0"
rand = "0.8.5"
